name: Deploy Site

on:
  push:
    branches:
      - master
    paths:
      - "site/**/*"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest Rust toolchain
        run: |
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Build Site
        run: yarn && yarn site:build
        working-directory: site
      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/site/.vitepress/dist
          cname: taplo.tamasfe.dev
